name: basefundi
description: "Aplicación Fundimetales Web"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  intl: ^0.20.2
  excel: ^4.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  firebase_messaging: ^15.2.7
  csv: ^6.0.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  universal_html: ^2.2.4
  permission_handler: ^11.3.1
  share_plus: ^11.0.0
  go_router: ^16.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logoappfm.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png 
    - lib/assets/logoletters.png
    - lib/assets/logoappfm.png
